name: Build Python 3.12 Wheel

on:
  push:
    branches: [ "main" ]

jobs:
  linux-x86_64:
    name: Build manylinux (x86_64)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install maturin
      - run: |
          maturin build --release --interpreter python3.12
      - uses: actions/upload-artifact@v4
        with:
          name: proto170-py312-wheel-x86_64
          path: target/wheels/*.whl

  linux-aarch64:
    name: Build manylinux (aarch64)
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_aarch64:latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python in container
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install maturin
      - run: |
          maturin build --release --manylinux aarch64 --interpreter python3.12
      - uses: actions/upload-artifact@v4
        with:
          name: proto170-py312-wheel-aarch64
          path: target/wheels/*.whl

  windows-build:
    name: Build Windows wheel (Python 3.12)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: |
          python -m pip install --upgrade pip
          pip install maturin
      - run: |
          maturin build --release --interpreter python
      - uses: actions/upload-artifact@v4
        with:
          name: proto170-windows-py312
          path: target/wheels/*.whl
