name: Build Python 3.12 Wheel

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Python + dependencies
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install maturin
        run: |
          python -m pip install --upgrade pip
          pip install maturin

      - name: Build manylinux wheel (Python 3.12)
        run: |
          maturin build --release --interpreter python3.12

      - name: Upload wheel as artifact
        uses: actions/upload-artifact@v4
        with:
          name: proto170-py312-wheel
          path: target/wheels/*.whl
