name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wheel:
    name: Build Linux wheel via maturin (manylinux)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build wheel in manylinux container
        run: |
          docker run --rm \
            -v "$PWD":/io \
            ghcr.io/pyo3/maturin \
            build --release --manylinux 2014 \
            -o /io/target/wheels

      - name: Upload built wheel
        uses: actions/upload-artifact@v4
        with:
          name: built-wheel
          path: target/wheels/*.whl
